const UPDATE_MANAGER_MODULE_SETTING = 'UPDATE_MANAGER_MODULE_SETTING';

const UPDATE_TEACHER_MODULE_SETTING = 'UPDATE_TEACHER_MODULE_SETTING';

const UPDATE_STUDENT_MODULE_SETTING = 'UPDATE_STUDENT_MODULE_SETTING';

export default {

    UPDATE_MANAGER_MODULE_SETTING,

    UPDATE_TEACHER_MODULE_SETTING,

    UPDATE_STUDENT_MODULE_SETTING

}