//课程详情弹窗开启和关闭
const SCHEDULE_DETAIL_MODAL_SHOW = 'SCHEDULE_DETAIL_MODAL_SHOW';

const SCHEDULE_DETAIL_MODAL_HIDE = 'SCHEDULE_DETAIL_MODAL_HIDE';

export default {

    SCHEDULE_DETAIL_MODAL_SHOW,

    SCHEDULE_DETAIL_MODAL_HIDE

}