

const STUDENT_SEARCH_LOADING_SHOW = 'STUDENT_SEARCH_LOADING_SHOW';

const STUDENT_SEARCH_LOADING_HIDE = 'STUDENT_SEARCH_LOADING_HIDE';


export default {

    STUDENT_SEARCH_LOADING_HIDE,

    STUDENT_SEARCH_LOADING_SHOW

}