//操作名称

//app层级的loading
const APP_LOADING_CLOSE = 'APP_LOADING_CLOSE';
const APP_LOADING_SHOW = 'APP_LOADING_SHOW';
//app层级的弹出层
const SHOW_ERROR_ALERT = 'SHOW_ERROR_ALERT';
const CLOSE_ERROR_ALERT = 'CLOSE_ERROR_ALERT';
//班级总览的loading
const GRADE_LOADING_SHOW = 'GRADE_LOADING_SHOW';
const GRADE_LOADING_HIDE = 'GRADE_LOADING_HIDE';
//某一年级的loaing
const CLASS_LOADING_SHOW = 'CLASS_LOADING_SHOW';
const CLASS_LOADING_HIDE = 'CLASS_LOADING_HIDE';
//某一具体班级的loading
const STUDENT_LOADING_HIDE = 'STUDENT_LOADING_HIDE';
const STUDENT_LOADING_SHOW = 'STUDENT_LOADING_SHOW';
//弹出一个添加班级的弹出层
const  ADD_CLASS_MODAL_SHOW = 'ADD_CLASS_MODAL_SHOW';
const  ADD_CLASS_MODAL_HIDE = 'ADD_CLASS_MODAL_HIDE';
//添加班级弹出层select改变
const ADD_CLASS_SELECT_CHANGE = 'ADD_CLASS_SELECT_CHANGE';

//将添加班级弹出层的input置为disabled或者可输入
const ADD_CLASS_INPUT_DISABLED = 'ADD_CLASS_INPUT_DISABLED';
const ADD_CLASS_INPUT_ABLED = 'ADD_CLASS_INPUT_ABLED';

//班级弹出层input 改变
const ADD_CLASS_INPUT_CHANGE = 'ADD_CLASS_INPUT_CHANGE';
//添加班级select的提示
const ADD_CLASS_SELECT_TIPS_SHOW = 'ADD_CLASS_SELECT_TIPS_SHOW';
const ADD_CLASS_SELECT_TIPS_HIDE = 'ADD_CLASS_SELECT_TIPS_HIDE';
const ADD_CLASS_SELECT_TIPS = 'ADD_CLASS_SELECT_TIPS';
//添加班级input的提示
const ADD_CLASS_INPUT_TIPS_SHOW = 'ADD_CLASS_INPUT_TIPS_SHOW';
const ADD_CLASS_INPUT_TIPS_HIDE = 'ADD_CLASS_INPUT_TIPS_HIDE';
const ADD_CLASS_INPUT_TIPS = 'ADD_CLASS_INPUT_TIPS';
//调班弹窗操作
const ADJUST_CLASS_MODAL_SHOW = 'ADJUST_CLASS_MODAL_SHOW';
const ADJUST_CLASS_MODAL_HIDE = 'ADJUST_CLASS_MODAL_HIDE';


//操作函数




export default {
    APP_LOADING_CLOSE,
    APP_LOADING_SHOW,
    SHOW_ERROR_ALERT,
    CLOSE_ERROR_ALERT,
    CLASS_LOADING_SHOW,
    CLASS_LOADING_HIDE,
    GRADE_LOADING_HIDE,
    GRADE_LOADING_SHOW,
    STUDENT_LOADING_HIDE,
    STUDENT_LOADING_SHOW,
    ADD_CLASS_MODAL_HIDE,
    ADD_CLASS_MODAL_SHOW,
    ADD_CLASS_INPUT_ABLED,
    ADD_CLASS_INPUT_DISABLED,
    ADD_CLASS_INPUT_CHANGE,
    ADD_CLASS_SELECT_CHANGE,
    ADD_CLASS_SELECT_TIPS_SHOW,
    ADD_CLASS_SELECT_TIPS_HIDE,
    ADD_CLASS_SELECT_TIPS,
    ADD_CLASS_INPUT_TIPS_SHOW,
    ADD_CLASS_INPUT_TIPS_HIDE,
    ADD_CLASS_INPUT_TIPS,
    ADJUST_CLASS_MODAL_SHOW,
    ADJUST_CLASS_MODAL_HIDE
}