const ADD_SCHEDULE_MODAL_SHOW = 'ADJUST_SCHEDULE_MODAL_SHOW';

const ADD_SCHEDULE_MODAL_HIDE = 'ADJUST_SCHEDULE_MODAL_HIDE';

export default {

    ADD_SCHEDULE_MODAL_SHOW,

    ADD_SCHEDULE_MODAL_HIDE

}