const STT_NOW_WEEK_CHANGE = 'STT_NOW_WEEK_CHANGE';

const LOADING_HIDE = 'LOADING_HIDE';

const TEACHER_LIST_UPDATE = 'TEACHER_LIST_UPDATE';

export default {

    STT_NOW_WEEK_CHANGE,

    LOADING_HIDE,

    TEACHER_LIST_UPDATE

}